package com.tesis.clinicapp.model;
// Generated 11-02-2016 09:42:18 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoExamen generated by hbm2java
 */
@Entity
@Table(name = "catalogo_examen", schema = "clinica")
public class CatalogoExamen implements java.io.Serializable {

	private int id;
	private Clasificacion clasificacion;
	private String nombre;
	private String descripcion;
	private Set<CatalogoItemsExamen> catalogoItemsExamens = new HashSet<CatalogoItemsExamen>(0);
	private Set<Examen> examens = new HashSet<Examen>(0);

	public CatalogoExamen() {
	}

	public CatalogoExamen(int id, Clasificacion clasificacion, String nombre, String descripcion) {
		this.id = id;
		this.clasificacion = clasificacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public CatalogoExamen(int id, Clasificacion clasificacion, String nombre, String descripcion,
			Set<CatalogoItemsExamen> catalogoItemsExamens, Set<Examen> examens) {
		this.id = id;
		this.clasificacion = clasificacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.catalogoItemsExamens = catalogoItemsExamens;
		this.examens = examens;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clasifiacion_id", nullable = false)
	public Clasificacion getClasificacion() {
		return this.clasificacion;
	}

	public void setClasificacion(Clasificacion clasificacion) {
		this.clasificacion = clasificacion;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoExamen")
	public Set<CatalogoItemsExamen> getCatalogoItemsExamens() {
		return this.catalogoItemsExamens;
	}

	public void setCatalogoItemsExamens(Set<CatalogoItemsExamen> catalogoItemsExamens) {
		this.catalogoItemsExamens = catalogoItemsExamens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoExamen")
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

}
