package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CitaMedica generated by hbm2java
 */
@Entity
@Table(name = "cita_medica", schema = "clinica")
public class CitaMedica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1662340974617987251L;
	private int idCitaMedica;
	private Expediente expediente;
	private Date fechaReserva;
	private Date horaDeReserva;
	private String descripcion;

	public CitaMedica() {
	}

	public CitaMedica(int idCitaMedica) {
		this.idCitaMedica = idCitaMedica;
	}

	public CitaMedica(int idCitaMedica, Expediente expediente, Date fechaReserva, Date horaDeReserva,
			String descripcion) {
		this.idCitaMedica = idCitaMedica;
		this.expediente = expediente;
		this.fechaReserva = fechaReserva;
		this.horaDeReserva = horaDeReserva;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "id_cita_medica", unique = true, nullable = false)
	public int getIdCitaMedica() {
		return this.idCitaMedica;
	}

	public void setIdCitaMedica(int idCitaMedica) {
		this.idCitaMedica = idCitaMedica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expediente_id")
	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_reserva", length = 13)
	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_de_reserva", length = 15)
	public Date getHoraDeReserva() {
		return this.horaDeReserva;
	}

	public void setHoraDeReserva(Date horaDeReserva) {
		this.horaDeReserva = horaDeReserva;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
