package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clasificacion generated by hbm2java
 */
@Entity
@Table(name = "clasificacion", schema = "clinica")
public class Clasificacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7905873427439247032L;
	private int idClasificacion;
	private String categoria;
	private String descripcion;
	private Set<Examen> examens = new HashSet<Examen>(0);

	public Clasificacion() {
	}

	public Clasificacion(int idClasificacion) {
		this.idClasificacion = idClasificacion;
	}

	public Clasificacion(int idClasificacion, String categoria, String descripcion, Set<Examen> examens) {
		this.idClasificacion = idClasificacion;
		this.categoria = categoria;
		this.descripcion = descripcion;
		this.examens = examens;
	}

	@Id

	@Column(name = "id_clasificacion", unique = true, nullable = false)
	public int getIdClasificacion() {
		return this.idClasificacion;
	}

	public void setIdClasificacion(int idClasificacion) {
		this.idClasificacion = idClasificacion;
	}

	@Column(name = "categoria")
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clasificacion")
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

}
