package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto", schema = "clinica")
public class Contacto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1594869193739176481L;
	private int idContacto;
	private Expediente expediente;
	private String direccion;
	private String municipio;
	private String departamento;
	private String email;
	private String telefono;

	public Contacto() {
	}

	public Contacto(int idContacto) {
		this.idContacto = idContacto;
	}

	public Contacto(int idContacto, Expediente expediente, String direccion, String municipio, String departamento,
			String email, String telefono) {
		this.idContacto = idContacto;
		this.expediente = expediente;
		this.direccion = direccion;
		this.municipio = municipio;
		this.departamento = departamento;
		this.email = email;
		this.telefono = telefono;
	}

	@Id

	@Column(name = "id_contacto", unique = true, nullable = false)
	public int getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(int idContacto) {
		this.idContacto = idContacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expediente_id")
	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "municipio")
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "departamento")
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
