package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "examen", schema = "clinica")
public class Examen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8388992053768394446L;
	private int idExamen;
	private Clasificacion clasificacion;
	private Expediente expediente;
	private Laboratorista laboratorista;
	private String nombreExamen;
	private String descripcion;
	private Set<ItemsExamenes> itemsExameneses = new HashSet<ItemsExamenes>(0);

	public Examen() {
	}

	public Examen(int idExamen) {
		this.idExamen = idExamen;
	}

	public Examen(int idExamen, Clasificacion clasificacion, Expediente expediente, Laboratorista laboratorista,
			String nombreExamen, String descripcion, Set<ItemsExamenes> itemsExameneses) {
		this.idExamen = idExamen;
		this.clasificacion = clasificacion;
		this.expediente = expediente;
		this.laboratorista = laboratorista;
		this.nombreExamen = nombreExamen;
		this.descripcion = descripcion;
		this.itemsExameneses = itemsExameneses;
	}

	@Id

	@Column(name = "id_examen", unique = true, nullable = false)
	public int getIdExamen() {
		return this.idExamen;
	}

	public void setIdExamen(int idExamen) {
		this.idExamen = idExamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clasifiacion_id")
	public Clasificacion getClasificacion() {
		return this.clasificacion;
	}

	public void setClasificacion(Clasificacion clasificacion) {
		this.clasificacion = clasificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expediente_id")
	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "laboratorista_id")
	public Laboratorista getLaboratorista() {
		return this.laboratorista;
	}

	public void setLaboratorista(Laboratorista laboratorista) {
		this.laboratorista = laboratorista;
	}

	@Column(name = "nombre_examen")
	public String getNombreExamen() {
		return this.nombreExamen;
	}

	public void setNombreExamen(String nombreExamen) {
		this.nombreExamen = nombreExamen;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examen")
	public Set<ItemsExamenes> getItemsExameneses() {
		return this.itemsExameneses;
	}

	public void setItemsExameneses(Set<ItemsExamenes> itemsExameneses) {
		this.itemsExameneses = itemsExameneses;
	}

}
