package com.tesis.clinicapp.model;
// Generated 11-02-2016 09:42:18 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "examen", schema = "clinica")
public class Examen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6539803448166927348L;
	private Long id;
	private CatalogoExamen catalogoExamen;
	private Laboratorista laboratorista;
	private Paciente paciente;
	private Date fechaProcesamiento;
	private String observaciones;
	private Set<ItemsExamen> itemsExamens = new HashSet<ItemsExamen>(0);

	public Examen() {
	}

	public Examen(CatalogoExamen catalogoExamen, Laboratorista laboratorista, Paciente paciente) {
		this.catalogoExamen = catalogoExamen;
		this.laboratorista = laboratorista;
		this.paciente = paciente;
	}

	public Examen(CatalogoExamen catalogoExamen, Laboratorista laboratorista, Paciente paciente,
			Date fechaProcesamiento, String observaciones, Set<ItemsExamen> itemsExamens) {
		this.catalogoExamen = catalogoExamen;
		this.laboratorista = laboratorista;
		this.paciente = paciente;
		this.fechaProcesamiento = fechaProcesamiento;
		this.observaciones = observaciones;
		this.itemsExamens = itemsExamens;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_examen_id", nullable = false)
	public CatalogoExamen getCatalogoExamen() {
		return this.catalogoExamen;
	}

	public void setCatalogoExamen(CatalogoExamen catalogoExamen) {
		this.catalogoExamen = catalogoExamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "laboratorista_id", nullable = false)
	public Laboratorista getLaboratorista() {
		return this.laboratorista;
	}

	public void setLaboratorista(Laboratorista laboratorista) {
		this.laboratorista = laboratorista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paciente_id", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_procesamiento", length = 13)
	public Date getFechaProcesamiento() {
		return this.fechaProcesamiento;
	}

	public void setFechaProcesamiento(Date fechaProcesamiento) {
		this.fechaProcesamiento = fechaProcesamiento;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examen")
	public Set<ItemsExamen> getItemsExamens() {
		return this.itemsExamens;
	}

	public void setItemsExamens(Set<ItemsExamen> itemsExamens) {
		this.itemsExamens = itemsExamens;
	}

}
