package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemsExamenes generated by hbm2java
 */
@Entity
@Table(name = "items_examenes", schema = "clinica")
public class ItemsExamenes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4346738154997699754L;
	private int idItemExamen;
	private Examen examen;
	private String descripcion;
	private String valorExamen;

	public ItemsExamenes() {
	}

	public ItemsExamenes(int idItemExamen) {
		this.idItemExamen = idItemExamen;
	}

	public ItemsExamenes(int idItemExamen, Examen examen, String descripcion, String valorExamen) {
		this.idItemExamen = idItemExamen;
		this.examen = examen;
		this.descripcion = descripcion;
		this.valorExamen = valorExamen;
	}

	@Id

	@Column(name = "id_item_examen", unique = true, nullable = false)
	public int getIdItemExamen() {
		return this.idItemExamen;
	}

	public void setIdItemExamen(int idItemExamen) {
		this.idItemExamen = idItemExamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "examen_id")
	public Examen getExamen() {
		return this.examen;
	}

	public void setExamen(Examen examen) {
		this.examen = examen;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valor_examen")
	public String getValorExamen() {
		return this.valorExamen;
	}

	public void setValorExamen(String valorExamen) {
		this.valorExamen = valorExamen;
	}

}
