package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Laboratorista generated by hbm2java
 */
@Entity
@Table(name = "laboratorista", schema = "clinica")
public class Laboratorista implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3836441663332099534L;
	private int idLaboratorista;
	private String nombre;
	private String apellido;
	private String profesion;
	private Integer edad;
	private String dui;
	private String nit;
	private String jvplc;
	private Set<Examen> examens = new HashSet<Examen>(0);

	public Laboratorista() {
	}

	public Laboratorista(int idLaboratorista) {
		this.idLaboratorista = idLaboratorista;
	}

	public Laboratorista(int idLaboratorista, String nombre, String apellido, String profesion, Integer edad,
			String dui, String nit, String jvplc, Set<Examen> examens) {
		this.idLaboratorista = idLaboratorista;
		this.nombre = nombre;
		this.apellido = apellido;
		this.profesion = profesion;
		this.edad = edad;
		this.dui = dui;
		this.nit = nit;
		this.jvplc = jvplc;
		this.examens = examens;
	}

	@Id

	@Column(name = "id_laboratorista", unique = true, nullable = false)
	public int getIdLaboratorista() {
		return this.idLaboratorista;
	}

	public void setIdLaboratorista(int idLaboratorista) {
		this.idLaboratorista = idLaboratorista;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido")
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "profesion")
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "dui")
	public String getDui() {
		return this.dui;
	}

	public void setDui(String dui) {
		this.dui = dui;
	}

	@Column(name = "nit")
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "jvplc")
	public String getJvplc() {
		return this.jvplc;
	}

	public void setJvplc(String jvplc) {
		this.jvplc = jvplc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "laboratorista")
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

}
