package com.tesis.clinicapp.model;
// Generated 11-02-2016 09:42:18 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", schema = "clinica")
public class Paciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7706793308653839954L;
	private Long id;
	private String nombres;
	private String apellidos;
	private char sexo;
	private int edad;
	private String dui;
	private String nit;
	private String nacionalidad;
	private String profesion;
	private String estadoCivil;
	private String municipio;
	private String departamento;
	private String direccion;
	private String email;
	private String telefono;
	private Set<Examen> examens = new HashSet<Examen>(0);
	private Set<Citas> citases = new HashSet<Citas>(0);

	public Paciente() {
	}

	public Paciente(String nombres, String apellidos, char sexo, int edad, String dui, String nit,
			String nacionalidad, String municipio, String departamento, String direccion, String telefono) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.edad = edad;
		this.dui = dui;
		this.nit = nit;
		this.nacionalidad = nacionalidad;
		this.municipio = municipio;
		this.departamento = departamento;
		this.direccion = direccion;
		this.telefono = telefono;
	}

	public Paciente(String nombres, String apellidos, char sexo, int edad, String dui, String nit,
			String nacionalidad, String profesion, String estadoCivil, String municipio, String departamento,
			String direccion, String email, String telefono, Set<Examen> examens, Set<Citas> citases) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.edad = edad;
		this.dui = dui;
		this.nit = nit;
		this.nacionalidad = nacionalidad;
		this.profesion = profesion;
		this.estadoCivil = estadoCivil;
		this.municipio = municipio;
		this.departamento = departamento;
		this.direccion = direccion;
		this.email = email;
		this.telefono = telefono;
		this.examens = examens;
		this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nombres", nullable = false)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	@Column(name = "edad", nullable = false)
	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	@Column(name = "dui", nullable = false)
	public String getDui() {
		return this.dui;
	}

	public void setDui(String dui) {
		this.dui = dui;
	}

	@Column(name = "nit", nullable = false)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "nacionalidad", nullable = false)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "profesion")
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "estado_civil")
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "municipio", nullable = false)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "departamento", nullable = false)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "direccion", nullable = false)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", nullable = false)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente",orphanRemoval=true)
	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	public Set<Citas> getCitases() {
		return this.citases;
	}

	public void setCitases(Set<Citas> citases) {
		this.citases = citases;
	}
	
	public String toString(){
		return this.nombres + " " + this.apellidos;
	}

}
