package com.tesis.clinicapp.model;
// Generated 10-05-2016 09:37:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PacienteDatos generated by hbm2java
 */
@Entity
@Table(name = "paciente_datos", schema = "clinica")
public class PacienteDatos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5343185452462976585L;
	private Long idPacienteDatos;
	private String nombres;
	private String apellidos;
	private Character sexo;
	private Integer edad;
	private String dui;
	private String nit;
	private String profesion;
	private String nacionalidad;
	private Set<Expediente> expedientes = new HashSet<Expediente>(0);

	public PacienteDatos() {
	}

	public PacienteDatos(String nombres, String apellidos, String dui, String nit) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.dui = dui;
		this.nit = nit;
	}

	public PacienteDatos(String nombres, String apellidos, Character sexo, Integer edad,
			String dui, String nit, String profesion, String nacionalidad, Set<Expediente> expedientes) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.edad = edad;
		this.dui = dui;
		this.nit = nit;
		this.profesion = profesion;
		this.nacionalidad = nacionalidad;
		this.expedientes = expedientes;
	}

	@Id
	//@SequenceGenerator(name = "MySequence", sequenceName = "paciente_datos_id_pacienteDatos_seq", allocationSize=1, schema = "clinica")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_paciente_datos", unique = true, nullable = false)
	public Long getIdPacienteDatos() {
		return this.idPacienteDatos;
	}

	public void setIdPacienteDatos(Long idPacienteDatos) {
		this.idPacienteDatos = idPacienteDatos;
	}

	@Column(name = "nombres", nullable = false)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "sexo", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "dui", nullable = false)
	public String getDui() {
		return this.dui;
	}

	public void setDui(String dui) {
		this.dui = dui;
	}

	@Column(name = "nit", nullable = false)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "profesion")
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "nacionalidad")
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacienteDatos")
	public Set<Expediente> getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set<Expediente> expedientes) {
		this.expedientes = expedientes;
	}

}
